### ISSUE TITLE
[BUG] huawei health to strava , Help!

### ISSUE THREAD

**Issue by NunoSilva1977** [aricooperdavis/Huawei-TCX-Converter#54]
C:\Users\Nuno Silva\Desktop\Strava\Hitrava-3.4.2>Hitrava.py --zip HiZip.zip --json_export
Info - External library xmlschema could not be imported.
It is required when using the --validate_xml argument.
It can be installed using: pip install xmlschema
2020-07-09 15:48:18,840 - ERROR - parse - Error parsing JSON file <./output/Motion path detail data & description/motion path detail data.json>
'recordDay'
Traceback (most recent call last):
  File "C:\Users\Nuno Silva\Desktop\Strava\Hitrava-3.4.2\Hitrava.py", line 1131, in parse
    activity_date = dts.strptime(str(activity_dict['recordDay']), "%Y%m%d").date()
KeyError: 'recordDay'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nuno Silva\Desktop\Strava\Hitrava-3.4.2\Hitrava.py", line 1897, in <module>
    main()
  File "C:\Users\Nuno Silva\Desktop\Strava\Hitrava-3.4.2\Hitrava.py", line 1884, in main
    hi_activity_list = hi_json.parse(args.from_date)
  File "C:\Users\Nuno Silva\Desktop\Strava\Hitrava-3.4.2\Hitrava.py", line 1276, in parse
    raise Exception('Error parsing JSON file <%s>', self.json_file.name)
Exception: ('Error parsing JSON file <%s>', './output/Motion path detail data & description/motion path detail data.json')

C:\Users\Nuno Silva\Desktop\Strava\Hitrava-3.4.2>pause
Press any key to continue . . .

**Anything else**
Was your run on the moon? Was your run 2 years long? Let me know anything out of the ordinary that might be relevant.

**Comment by aricooperdavis** [comment]
This is the wrong repository for that bug I believe. Are you looking for [Hitrava](https://github.com/CTHRU/Hitrava)? :)
